{
    'name' : 'Gym Management App',
    'author': "Edge Technologies",
    'version' : '14.0.1.0',
    'live_test_url':'https://youtu.be/0RpkD0L_xvs',
    "images":['static/description/main_screenshot.png'],
    'summary' : 'Apps helps to manage gym members gym trainers booking gym workout plan gym membership gym diet plan gym bmi weight gym exercise gym management system gym process spa and saloon management gym diet template gym workout planning',
    'description' : """
        This app helps user to manage gym members, gym trainers, workout plan, diet plan, bmi, weight, exercise overview etc.
    """,
    "license" : "OPL-1",
    'depends' : ['base','hr','account'],
    'data': [
            'security/gym_rule.xml',
            'security/ir.model.access.csv',
            'wizard/workout_schedule_report.xml',
            'wizard/view_buy_membership.xml',
            'views/view_gym_members.xml',
            'views/view_gym_trainers.xml',
            'views/view_trainer_skill.xml',
            'views/gym_days.xml',
            'views/view_diet_interval.xml',
            'views/view_gym_equipment.xml',
            'views/view_body_parts.xml',
            'views/view_gym_membership.xml',
            'views/view_bmi_calculation.xml',
            'views/view_member_weight.xml',
            'views/view_gym_exercise.xml',
            'views/view_gym_workout.xml',
            'views/view_diet_food.xml',
            'wizard/view_workout_schedule.xml',
            'wizard/view_diet_schedule.xml',
            'wizard/diet_schedule_report.xml',
            'report/schedule_workout_report_template.xml',
            'report/schedule_diet_report_template.xml',
            'report/workout_schedule_report.xml',
            'data/member_sequence.xml',
            'data/days_data.xml',
            'data/trainer_skill_data.xml',
            'data/diet_interval_data.xml',
            'data/body_parts_data.xml',
            ],
    'qweb' : [],
    'demo' : [],
    'installable' : True,
    'auto_install' : False,
    'price': 38,
    'currency': "EUR",
    'category' : 'Extra Tools',
}
